blueprint:
  homeassistant:
    min_version: 2024.6.0
  name: F1 Sensor - Track Status Light (Modern)
  description: >
    Turn a light into an F1 race-status indicator with sensible defaults and optional advanced controls.

    Setup in short: select session and track sensors, choose active session phases, select your light target, then adjust colors and optional gates.

    Track status values: CLEAR, YELLOW, VSC, SC, RED. Session phase values: pre, live, suspended, break, finished, finalised, ended.

    Optional gates can require at least one device at home, a media player state, and a do-not-disturb time window (including overnight windows).

    When session leaves active phases, you can keep the current light state, turn the light off, or set a neutral color after a delay.

    Optional notification actions support phone notifications, TTS, scripts, and other Home Assistant services.

    For testing, simulate session and track sensor states in Developer Tools -> States.
  domain: automation
  source_url: https://github.com/Nicxe/f1_sensor
  author: Nicxe
  input:
    data_sources:
      name: Data Sources
      icon: mdi:database
      collapsed: false
      description: Link the blueprint to your F1 Sensor entities.
      input:
        session_status_entity:
          name: Session Status Sensor
          description: Use the F1 Sensor entity that exposes session phase values such as live and finished.
          selector:
            entity:
              filter:
                - domain: sensor
              multiple: false
        track_status_entity:
          name: Track Status Sensor
          description: Use the F1 Sensor entity that exposes CLEAR, YELLOW, VSC, SC, and RED.
          selector:
            entity:
              filter:
                - domain: sensor
              multiple: false
        active_session_phases:
          name: Active Session Phases
          description: Light updates run only when session status is in one of these phases.
          default:
            - live
            - suspended
          selector:
            select:
              mode: dropdown
              multiple: true
              options:
                - label: Pre-session
                  value: pre
                - label: Live
                  value: live
                - label: Suspended
                  value: suspended
                - label: Break
                  value: break
                - label: Finished
                  value: finished
                - label: Finalised
                  value: finalised
                - label: Ended
                  value: ended

    activation_conditions:
      name: Activation Conditions
      icon: mdi:filter-check
      collapsed: true
      description: Optional conditions that must pass before light updates are applied.
      input:
        presence_devices:
          name: Presence Devices
          description: Optional. If selected, at least one device must be home.
          default: []
          selector:
            entity:
              filter:
                - domain: device_tracker
              multiple: true
        media_player_gate:
          name: Media Player Gate
          description: Optional. If selected, media player must be on, idle, or playing.
          default: ""
          selector:
            entity:
              filter:
                - domain: media_player
              multiple: false
        enable_dnd:
          name: Enable Do Not Disturb Window
          description: When enabled, light updates are blocked inside the configured time window.
          default: false
          selector:
            boolean: {}
        dnd_start_time:
          name: DND Start Time
          description: Start of do-not-disturb window.
          default: "23:00:00"
          selector:
            time: {}
        dnd_end_time:
          name: DND End Time
          description: End of do-not-disturb window.
          default: "07:00:00"
          selector:
            time: {}

    light_behavior:
      name: Light Behavior
      icon: mdi:lightbulb
      collapsed: false
      description: Choose the light target and default brightness/transition.
      input:
        light_target:
          name: Light Entity
          description: Light that will follow track status updates.
          selector:
            entity:
              filter:
                - domain: light
              multiple: false
        brightness_pct:
          name: Brightness
          description: Brightness used when turning the light on.
          default: 100
          selector:
            number:
              min: 0
              max: 100
              step: 1
              unit_of_measurement: "%"
        transition_s:
          name: Transition Time
          description: Transition duration for color changes.
          default: 1
          selector:
            number:
              min: 0
              max: 10
              step: 0.5
              unit_of_measurement: s

    flag_colors:
      name: Flag Colors
      icon: mdi:palette
      collapsed: true
      description: Set colors for standard race control statuses.
      input:
        color_clear:
          name: Color - CLEAR
          description: Color used when track status is CLEAR.
          default: [0, 255, 0]
          selector:
            color_rgb: {}
        color_yellow:
          name: Color - YELLOW
          description: Color used when track status is YELLOW.
          default: [255, 255, 0]
          selector:
            color_rgb: {}
        color_red:
          name: Color - RED
          description: Color used when track status is RED.
          default: [255, 0, 0]
          selector:
            color_rgb: {}

    safety_car_behavior:
      name: Safety Car Behavior
      icon: mdi:car-emergency
      collapsed: true
      description: Configure SC/VSC colors and optional flashing behavior.
      input:
        color_vsc:
          name: Color - VSC
          description: Color used when track status is VSC.
          default: [255, 255, 0]
          selector:
            color_rgb: {}
        color_sc:
          name: Color - SC
          description: Color used when track status is SC.
          default: [255, 0, 0]
          selector:
            color_rgb: {}
        flash_sc_vsc:
          name: Flash During SC and VSC
          description: If enabled, the light flashes while status remains SC or VSC.
          default: true
          selector:
            boolean: {}
        flash_interval_s:
          name: Flash Interval
          description: Seconds between on and off while flashing.
          default: 1
          selector:
            number:
              min: 1
              max: 10
              step: 1
              unit_of_measurement: s

    session_end_behavior:
      name: Session End Behavior
      icon: mdi:flag-checkered
      collapsed: true
      description: Configure what happens when session leaves active race phases.
      input:
        end_delay_min:
          name: End Delay
          description: Delay in minutes before applying the end-of-session action.
          default: 0
          selector:
            number:
              min: 0
              max: 240
              step: 1
              unit_of_measurement: min
        end_action:
          name: End Action
          description: Action to run after delay when session leaves active phases.
          default: keep
          selector:
            select:
              mode: dropdown
              options:
                - label: Keep current light state
                  value: keep
                - label: Turn off light
                  value: turn_off
                - label: Set neutral color
                  value: neutral
        end_neutral_color:
          name: Neutral Color
          description: Used only when End Action is set to neutral.
          default: [255, 255, 255]
          selector:
            color_rgb: {}

    notifications:
      name: Notifications (Optional)
      icon: mdi:bell-badge
      collapsed: true
      description: Run your own notification action sequence on track updates and/or session-end transitions.
      input:
        enable_notifications:
          name: Enable Notifications
          description: Master switch for optional notification actions.
          default: false
          selector:
            boolean: {}
        notify_on_track_updates:
          name: Notify on Track Status Updates
          description: Send notifications when track status changes and update conditions are valid.
          default: true
          selector:
            boolean: {}
        notify_on_session_end:
          name: Notify on Session End
          description: Send notifications when session leaves active phases.
          default: true
          selector:
            boolean: {}
        notification_actions:
          name: Notification Actions
          description: >
            Define any Home Assistant actions for notifications (phone, notify service, TTS, script, etc).
            Available templates: {{ notification_title }}, {{ notification_message }}, {{ notification_track_state }}, {{ notification_session_phase }}.
          default: []
          selector:
            action: {}

variables:
  track_status_entity: !input track_status_entity
  session_status_entity: !input session_status_entity
  active_phases: !input active_session_phases
  presence_list: !input presence_devices
  media_player_entity: !input media_player_gate
  enable_dnd_window: !input enable_dnd
  dnd_start: !input dnd_start_time
  dnd_end: !input dnd_end_time
  flash_enabled: !input flash_sc_vsc
  flash_interval: !input flash_interval_s
  end_action_mode: !input end_action
  notifications_enabled: !input enable_notifications
  notifications_on_track: !input notify_on_track_updates
  notifications_on_session_end: !input notify_on_session_end
  notification_actions_list: !input notification_actions
  has_notification_actions: "{{ notification_actions_list | count > 0 }}"
  track_state: "{{ states(track_status_entity) | upper }}"
  session_phase: "{{ states(session_status_entity) | lower }}"
  is_active_phase: "{{ session_phase in active_phases }}"
  presence_ok: >
    {% if presence_list | count == 0 %}
      true
    {% else %}
      {{ expand(presence_list) | selectattr('state', 'eq', 'home') | list | count > 0 }}
    {% endif %}
  media_ok: >
    {% if media_player_entity | string | length == 0 %}
      true
    {% else %}
      {{ states(media_player_entity) in ['on', 'idle', 'playing'] }}
    {% endif %}
  dnd_blocked: >
    {% if not enable_dnd_window %}
      false
    {% else %}
      {% set now_s = now().hour * 3600 + now().minute * 60 + now().second %}
      {% set start_parts = dnd_start.split(':') %}
      {% set end_parts = dnd_end.split(':') %}
      {% set start_s = (start_parts[0] | int(0)) * 3600 + (start_parts[1] | int(0)) * 60 + (start_parts[2] | int(0)) %}
      {% set end_s = (end_parts[0] | int(0)) * 3600 + (end_parts[1] | int(0)) * 60 + (end_parts[2] | int(0)) %}
      {{ (start_s <= end_s and start_s <= now_s <= end_s) or (start_s > end_s and (now_s >= start_s or now_s <= end_s)) }}
    {% endif %}
  session_left_active: >
    {% if trigger.id != 'session_update' %}
      false
    {% else %}
      {% set from_phase = (trigger.from_state.state if trigger.from_state is not none else '') | lower %}
      {% set to_phase = (trigger.to_state.state if trigger.to_state is not none else '') | lower %}
      {{ from_phase in active_phases and to_phase not in active_phases }}
    {% endif %}
  can_apply_track_light: >
    {{ is_active_phase and presence_ok and media_ok and not dnd_blocked }}

trigger:
  - platform: state
    entity_id: !input track_status_entity
    id: track_update
  - platform: state
    entity_id: !input session_status_entity
    id: session_update

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ session_left_active }}"
        sequence:
          - delay:
              minutes: !input end_delay_min
          - condition: template
            value_template: "{{ states(session_status_entity) | lower not in active_phases }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ end_action_mode == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input light_target
              - conditions:
                  - condition: template
                    value_template: "{{ end_action_mode == 'neutral' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_target
                    data:
                      brightness_pct: !input brightness_pct
                      rgb_color: !input end_neutral_color
                      transition: !input transition_s
          - if:
              - condition: template
                value_template: "{{ notifications_enabled and notifications_on_session_end and has_notification_actions }}"
            then:
              - variables:
                  notification_title: "F1 Session Ended"
                  notification_track_state: "{{ states(track_status_entity) | upper }}"
                  notification_session_phase: "{{ states(session_status_entity) | lower }}"
                  notification_message: >-
                    Session moved from
                    {{ (trigger.from_state.state if trigger.from_state is not none else 'unknown') | lower }}
                    to
                    {{ (trigger.to_state.state if trigger.to_state is not none else 'unknown') | lower }}.
                    Current track status: {{ states(track_status_entity) | upper }}.
              - sequence: !input notification_actions
      - conditions:
          - condition: template
            value_template: "{{ can_apply_track_light and track_state in ['CLEAR', 'YELLOW', 'RED', 'SC', 'VSC'] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ track_state == 'CLEAR' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_target
                    data:
                      brightness_pct: !input brightness_pct
                      rgb_color: !input color_clear
                      transition: !input transition_s
              - conditions:
                  - condition: template
                    value_template: "{{ track_state == 'YELLOW' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_target
                    data:
                      brightness_pct: !input brightness_pct
                      rgb_color: !input color_yellow
                      transition: !input transition_s
              - conditions:
                  - condition: template
                    value_template: "{{ track_state == 'RED' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_target
                    data:
                      brightness_pct: !input brightness_pct
                      rgb_color: !input color_red
                      transition: !input transition_s
              - conditions:
                  - condition: template
                    value_template: "{{ track_state == 'SC' }}"
                sequence:
                  - if:
                      - condition: template
                        value_template: "{{ flash_enabled }}"
                    then:
                      - repeat:
                          while:
                            - condition: template
                              value_template: >
                                {{ states(track_status_entity) | upper == 'SC' }}
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: !input light_target
                              data:
                                brightness_pct: !input brightness_pct
                                rgb_color: !input color_sc
                            - delay:
                                seconds: !input flash_interval_s
                            - service: light.turn_off
                              target:
                                entity_id: !input light_target
                            - delay:
                                seconds: !input flash_interval_s
                    else:
                      - service: light.turn_on
                        target:
                          entity_id: !input light_target
                        data:
                          brightness_pct: !input brightness_pct
                          rgb_color: !input color_sc
                          transition: !input transition_s
              - conditions:
                  - condition: template
                    value_template: "{{ track_state == 'VSC' }}"
                sequence:
                  - if:
                      - condition: template
                        value_template: "{{ flash_enabled }}"
                    then:
                      - repeat:
                          while:
                            - condition: template
                              value_template: >
                                {{ states(track_status_entity) | upper == 'VSC' }}
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: !input light_target
                              data:
                                brightness_pct: !input brightness_pct
                                rgb_color: !input color_vsc
                            - delay:
                                seconds: !input flash_interval_s
                            - service: light.turn_off
                              target:
                                entity_id: !input light_target
                            - delay:
                                seconds: !input flash_interval_s
                    else:
                      - service: light.turn_on
                        target:
                          entity_id: !input light_target
                        data:
                          brightness_pct: !input brightness_pct
                          rgb_color: !input color_vsc
                          transition: !input transition_s
          - if:
              - condition: template
                value_template: "{{ notifications_enabled and notifications_on_track and has_notification_actions and trigger.id == 'track_update' }}"
            then:
              - variables:
                  notification_title: "F1 Track Status"
                  notification_track_state: "{{ states(track_status_entity) | upper }}"
                  notification_session_phase: "{{ states(session_status_entity) | lower }}"
                  notification_message: >-
                    Track status changed to {{ states(track_status_entity) | upper }}
                    during session phase {{ states(session_status_entity) | lower }}.
              - sequence: !input notification_actions

mode: restart
